### PR TITLE
Julia v0.4 compatibility changes.

### PR DESCRIPTION
**Pull request by omus**
Tested changes on Julia 0.3.10 and 0.4.0-dev+5629.

### CODE REVIEW

**Comment by iamed2** [comment]
@omus https://travis-ci.org/JuliaDB/PostgreSQL.jl/jobs/69471749

Segfaults consistently on 0.4

**Comment by omus** [comment]
I cannot reproduce this segfault. I'll note that I didn't change anything specific to the DB connection so I expect that this issue was present prior to my changes. Can you attempt to re-run Travis on the latest version of Julia for this PR and for the latest PostgreSQL master?

**Comment by iamed2** [comment]
@omus try changing the `postgresql` apt package to `postgresql-9.4`. Pushing will trigger a rebuild.

**Comment by omus** [comment]
Inspecting the travis log again I noticed that the test cases were running via:

```
julia --check-bounds=yes --code-coverage=user --inline=no --color=no ~/.julia/v0.4/PostgreSQL/test/runtests.jl
```

Which does produce a segfault on my local system. It appears the issue is `--inline=no`. I'll try to determine why this parameter is causing issues.

**Comment by omus** [comment]
@iamed2 I believe you'll need to investigate. It appears that using any libpq function that modifies the internals of a `Ptr` such as `PQfinish`, `PQclear`, or `PQfreemem` will all generate a segfault when running the tests.

**Comment by iamed2** [comment]
Please edit PR to compare against compat

**Pull request closed without merging**
