### PR TITLE
Add copy functionality.

### PR DESCRIPTION
**Pull request by syadlowsky**
I've added a copy function. This is, unfortunately, not defined in the DBI interface, so I added it as a separate function of PostgreSQL.

### CODE REVIEW

**Comment by iamed2** [comment]
This looks good; just please add a test :)

**Comment by syadlowsky** [comment]
Added a test. The decreased coverage is an all-hell-breaks-loose type of error for which I check, but don't know how to test without the database dying in between.

**Comment by iamed2** [comment]
I just noticed you don't check the error status of `PQputCopyData`; please do that. You can move the existing error code you wrote into a function and call that function each time; that way you can test the error code by just providing a malformed CSV file.

**Comment by iamed2** [comment]
Excellent, thanks!

**Pull request merged**
